config/routes.rb
Rails.application.routes.draw do


  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  resources :users, only: [:show, :edit, :index, :update]

  resources :books do
    resource :favorites, only: [:create, :destroy]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  
  has_many :favorites, dependent: :destroy

  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no-image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    @books = Book.all

    if  @book.save
     redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      render :index
    end
  end


  def show
    @book = Book.new
    @user = Book.find(params[:id])
  end

  def edit
    @book =Book.find(params[:id])
    if @book.user.id == current_user.id
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorites = current_user.favorites.new(book_id: book.id)
    favorites.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorites = current_user.favorites.find_by(params[:book_id])
    favorites.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
   @user = User.find(params[:id])
   if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
   else
    render :edit
   end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_list.html.erb
<h2>Books</h2>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td><%= link_to user_path(book.user.id) do %><%= image_tag book.user.get_profile_image(80, 80) %><% end %></td>
      <td><%= link_to book.title, book_path(book.id)%></td>
      <td><%= book.body %></td>
      <td><%= render 'favorites/favorite_btn', book: book %></td>
    </tr>
    <% end %>
  </tbody>


</table>

app/views/books/_error_message.html.erb
<% if book.errors.any? %>
  <h3><%= book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/books/_user_info.html.erb
     <h2> User Info</h2>
     <%= image_tag user.get_profile_image(63, 63) %>
     <table class="table">
       <tbody>
         <tr>
           <th>name</th>
           <th><%= user.name %></th>
         </tr>
         <tr>
           <th>introduction</th>
           <th><%= user.introduction %></th>
         </tr>
       </tbody>
     </table>

     <div class="row">
         <%= link_to (edit_user_path(user.id)), class: 'btn btn-outline-secondary btn-block btn-sm' do %><i class="fas fa-user-cog"></i><% end %>

     </div>

     <h2 class="mt-3">New book</h1>
     <%= form_with model: @book do |f| %>
     <div class="form-group">
       <%= f.label :title %><br />
       <%= f.text_field :title, class:'form-control' %>
     </div>

     <div class="form-group">
       <%= f.label :Opinion %><br />
       <%= f.text_area :body, class:'form-control' %>
     </div>

     <div class="form-group">
       <%= f.submit "Create Book", class:"btn btn-success" %>
     </div>

     <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>Editing Book</h1>
      <%= render 'error_message', book: @book %>

      <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
      <div class="form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :Opinion %><br />
        <%= f.text_area :body, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class:'btn btn-success' %>
      </div>

      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
      <% end %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
　<%= render 'error_message', book: @book %>

  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info', user: @user %>

      <div class="col-md-8 offset-md-1">
       <%= render 'book_list', books: @books %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <%= render 'error_message', book: @book %>

  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info', user: @user.user %>

      <div class="col-md-8 offset-md-1">
       <h2>Book detail</h2>
       <table class="table">
         <tr>
           <td><%= link_to (user_path(@user.user.id)) do %><%= image_tag @user.user.get_profile_image(100, 100) %><br>
               <%= @user.user.name %><% end %></td>
           <td><%= link_to @user.title, book_path(@user.id) %></td>
           <td><%= @user.body %></td>
           <td><%= render 'favorites/favorite_btn', book: @user %></td>
           <% if @user.user.id == current_user.id %>
             <td><%= link_to "Edit", edit_book_path(@user.id), class:'btn btn-success btn-sm' %></td>
             <td><%= link_to "Destroy", book_path(@user.id), method: :delete, "data-confirm" => "本当に消しますか?", class:'btn btn-danger btn-sm' %></td>
          <% end %>
         </tr>
       </table>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, style:'color: red;' do %>
      <i class="fas fa-heart"></i>
      <%= book.favorites.count %>
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post do %>
      <i class="far fa-heart"></i>
      <%= book.favorites.count %>
    <% end %>
  </p>

<% end %>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Booksers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Booksers</strong>!!</h1>

      <p>In <i class="fas fa-book"></i><strong>Booksers</strong>,</p>
      <p>yuo can share and exhange your opinions, inpressions, and emotions</p>

      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
         <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block" %>
         <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
        </div>

      </div>


    </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white ">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to (user_path(current_user&.id)), class:'nav-link text-white' do  %><i class="fas fa-home"></i> Home<% end %></li>

                <li class="nav-item">
                  <%= link_to (users_path), class:'nav-link text-white' do %><i class="fas fa-users"></i> Users<% end %></li>
                <li class="nav-item">
                  <%= link_to (books_path), class:'nav-link text-white' do %><i class="fas fa-book-open"></i> Books<% end %></li>
                <li class="nav-item">
                  <%= link_to (destroy_user_session_path), class: 'nav-link text-white', method: :delete do %><i class="fas fa-sign-out-alt"></i> Log out<% end %></li>

              <% else %>
                <li class="nav-item">
                  <%= link_to (root_path), class:'nav-link text-white' do  %><i class="fas fa-home"></i> Home<% end %></li>

                <li class="nav-item">
                  <%= link_to (about_path), class:'nav-link text-white' do %><i class="fas fa-link"></i> About<% end %></li>
                <li class="nav-item">
                  <%= link_to (new_user_registration_path), class:'nav-link text-white' do %><i class="fas fa-user-plus"></i> Sign up<% end %></li>
                <li class="nav-item">
                  <%= link_to (new_user_session_path), class:'nav-link text-white' do %><i class="fas fa-sign-in-alt"></i></i> Log in<% end %></li>
              <% end %>
             </ul>
          </div>
        </div>


      </nav>
    </header>

    <main>
      　　<%= notice %>
          <%= yield %>

    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratoo.inc</p>


          </div>
        </div>
      </div>

    </footer>


  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto" >
      <h2>User info</h2>
      <%= render 'books/error_message', book: @user %>

      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus: true,  id:"inputName", class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :image %><br />
          <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :Introduction %><br />
          <%= f.text_area :introduction, class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class:'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error_message', book: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/user_info', user: @user %>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
             <tr>
               <td><%= image_tag user.get_profile_image(80, 80) %></td>
               <td><%= user.name %></td>
               <td><%= link_to "Show", user_path(user.id) %></td>
             </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error_message', book: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/user_info', user: @user %>

      <div class="col-md-8 offset-md-1">
        <%= render 'books/book_list', books: @books %>

      </div>
    </div>
  </div>
</div>